name: Build LLVM XCFrameworks for Release
on: [push]
jobs:
  prepare-build-tools:
    runs-on: macos-11
    if: ${{ false }}
    steps:
      - uses: actions/checkout@v3
      - run: ./build-tools.sh
      - run: |
          curl -OL https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-mac.zip
          unzip ninja-mac.zip
          mv ninja tools/bin
      - run: tar -zcvf tools.zip tools/
      - uses: actions/upload-artifact@v3
        with:
          name: tools
          path: tools.zip

  build-libffi:
    runs-on: macos-11
    strategy:
      matrix:
        platformArch: [iphoneos, iphonesimulator, iphonesimulator-arm64, maccatalyst, maccatalyst-arm64]
    steps:
      - uses: actions/checkout@v3
      - name: Build libffi for ${{ matrix.platformArch }}
        run: source build-llvm.sh && build_libffi ${{ matrix.platformArch }}
      - run: tar -zcvf libffi-${{ matrix.platformArch }}.zip libffi-${{ matrix.platformArch }}/
      - uses: actions/upload-artifact@v3
        with:
          name: libffi-${{ matrix.platformArch }}
          path: libffi-${{ matrix.platformArch }}.zip

  build-llvm:
    needs: build-libffi # prepare-build-tools
    runs-on: macos-12
    strategy:
      matrix:
        platformArch: [iphoneos, iphonesimulator, iphonesimulator-arm64, maccatalyst, maccatalyst-arm64]
    timeout-minutes: 1200
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - name: Extract artifacts
        run: find . -name "*.zip" -exec tar xzf {} \;
      - run: brew install ninja
      - name: Build LLVM for ${{ matrix.platformArch }}
        run: source build-llvm.sh && build_llvm ${{ matrix.platformArch }}
      - run: tar -zcvf LLVM-${{ matrix.platformArch }}.zip LLVM-${{ matrix.platformArch }}/
      - uses: actions/upload-artifact@v3
        with:
          name: LLVM-${{ matrix.platformArch }}
          path: LLVM-${{ matrix.platformArch }}.zip

  create-xcframework:
    needs: build-llvm
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - name: Extract artifacts
        run: find . -name "*.zip" -exec tar xzf {} \;

      - name: Create XCFramework for Intel Macs
        run: source build-llvm.sh && create_xcframework iphoneos iphonesimulator maccatalyst
      - run: tar -zcvf LLVM_Intel.xcframework.zip LLVM.xcframework
      - uses: actions/upload-artifact@v3
        with:
          name: LLVM_Intel
          path: LLVM_Intel.xcframework.zip

      - uses: actions/upload-artifact@v3
        with:
          name: libclang
          path: libclang.zip

      - name: Create XCFramework for M1 Macs
        run: source build-llvm.sh && rm -rf LLVM.xcframework && create_xcframework iphoneos iphonesimulator-arm64 maccatalyst-arm64
      - run: tar -zcvf LLVM_M1.xcframework.zip LLVM.xcframework
      - uses: actions/upload-artifact@v3
        with:
          name: LLVM_M1
          path: LLVM_M1.xcframework.zip
